parameters:
    amp1:
        val: 1.
        active: False
        lb: 0.
        ub: 10.
    amp2:
        val: 1.
        active: False
        lb: 0.
        ub: 10.
    amp3:
        val: 1.
        active: False
        lb: 0.
        ub: 10.
    lam:
        val: 526.5
        active: False
        lb: 523.
        ub: 528.
    Te:
        val: .5
        active: False
        lb: 0.01
        ub: 3.
        gradient: 0.0
    Ti:
        val: .2
        active: False
        lb: 0.01
        ub: 3.
    Z:
        val: 1.
        active: False
        lb: 1.
        ub: 25.
    A:
        val: 40
        active: False
    fract:
        val: 1
        active: False
    ne:
        val: .2
        active: False
        lb: .001
        ub: 10.
        gradient: 0.0
    ud:
        val: 0
        active: False
    Va:
        val: 0
        active: False
    m:
        val: 2.
        active: False
        lb: 2.
        ub: 5.
    fe:
        val: []
        active: False
        length: 3999
        type:
            DLM:
        lb: -100.
        ub: -0.5
        fe_decrease_strict: True
    blur:
        val: []
        active: False
        lb: 0.
        ub: 10.
    specCurvature:
        val: []
        active: False
        lb: .1
        ub: 10.
    fitprops:
        val: []
        active: False

other:
    crop_window: 256
    BinWidth: 10
    NumBinInRng: 0
    TotalNumBin: 1023
    expandedions: False
    extraoptions:
        load_ion_spec: False
        load_ele_spec: True
        fit_IAW: False
        fit_EPWb: True
        fit_EPWr: True
    PhysParams:
        background: [0, 0]
        norm: 0
    iawoff: 0
    iawfilter: [1, 4, 24, 528]
    CCDsize: [1024, 1024]
    flatbg: 0
    gain: 1
    points_per_pixel: 2
    ang_res_unit: 10
    lam_res_unit: 5
    refit_thresh: 5

data:
    shotnum: 101675
    shotDay: False
    fit_rng:
        blue_min: 450
        blue_max: 510
        red_min: 540
        red_max: 625
    bgscaleE: 1.0
    bgscaleI: 0.1
    bgshotmult: 1
    dpixel: 2
    lineouts:
        type:
            pixel
        start: 500
        end: 502
        skip: 1
    background:
        type:
            pixel
        slice: 900


    
optimizer:
    # use adam for nn / stochastic gradient descent
    # use L-BFGS-B for full batch / parameter learning
    # although adam will work here too
    method: l-bfgs-b
    hessian: False
    y_norm: True
    x_norm: False
    grad_method: AD
    batch_size: 2
    num_epochs: 200
    learning_rate: 1.0e-4
    parameter_norm: True

nn:
    use: false
    conv_filters: 32|16|16 #|32|32
    linear_widths: 32|16

dist_fit:
    window:
        len: 256 #should be even
        type: hamming # one of [hamming, hann, bartlett]

mlflow:
    experiment: inverse-thomson-scattering
    run: base